### ISSUE TITLE
Similar Projects

### ISSUE THREAD

**Issue by popey456963** [DoctorMcKay/node-binaryjson#1]
Hello, was reading through this code.  Is it similar to [MsgPack](https://msgpack.org/index.html) or [BSON](http://bsonspec.org/)?  It's a nice idea, and I wouldn't immediately say it's slower & has less compression than GZIP.  One would imagine the main reason for slower speed is that you're writing in JavaScript as opposed to C.

**Comment by DoctorMcKay** [comment]
It's similar to both MsgPack and BSON, yes (and I was aware of the existence of both at the time of writing this). To my knowledge, MsgPack and BSON don't make any attempt to optimize key names, so if you have an array of 500 objects all with the same keys, those key strings will be repeated 500 times. That's where JSON + GZIP really shines.

And considering slower speed, I compared binaryjson to JSON + GZIP both in Node and JSON + GZIP was quite a bit faster.
